name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: yuml-parser-linux
            exe_name: main
          - os: windows-latest
            artifact_name: yuml-parser-windows.exe
            exe_name: main.exe
          - os: macos-latest
            artifact_name: yuml-parser-macos
            exe_name: main

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install pyinstaller

      - run: pyinstaller --onefile main.py

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/${{ matrix.exe_name }}